### ISSUE TITLE
Question :can we have integration with Travis ci ?

### ISSUE THREAD

**Issue by r-sreesaran** [Wildcraft/jdk9-features#2]
Question :can we have integration with Travis ci ?. This will help us run test against various versions of java.

**Comment by narendranss** [comment]
Sure we can. Will it work on JDK 9? This project requires JDK 9 and we are working with Maven, it requires maven support as well. Please create a pull request with required travis.yml.

**Comment by r-sreesaran** [comment]
Need to try it out, I start the experimentation. We also need to include a
web hook. And join in slack so that we can communicate easily

**Comment by narendranss** [comment]
For now, we shall continue with GitHub itself for communication. For project management, we shall use the kanban - https://github.com/orgs/Wildcraft/projects/1
If the team grows bigger, we shall invest in other means.

**Comment by narendranss** [comment]
Current Travis build downloads a fresh copy of jdk9, it also fails. Please check the below link for details.
Do you think anything is missed out?
https://travis-ci.org/Wildcraft/jdk9-features

**Comment by narendranss** [comment]
@r-sreesaran Made some changes to the travis configuration and skipped some tests to make the build pass. Thanks for the effort sree.
